# Generated by Django 3.2.15 on 2024-05-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
