# Generated by Django 3.2.15 on 2024-05-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0002_auto_20240505_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
