# Generated by Django 3.2.15 on 2024-05-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_web', '0003_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanGeneratedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='output_generated/images/')),
            ],
        ),
    ]
