# Generated by Django 3.2.15 on 2024-05-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0004_gangeneratedmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gangeneratedmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='gangeneratedmodel',
            name='generated_Img',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='gangeneratedmodel',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
