# Generated by Django 3.2.15 on 2024-05-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0005_auto_20240514_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voxel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='model', max_length=50)),
                ('data', models.BinaryField()),
            ],
        ),
    ]
