# Generated by Django 3.2.15 on 2024-05-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0006_voxel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voxel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
